apiVersion: v1
kind: Service
metadata:
  name: backend-active
  namespace: prod
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  namespace: prod
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: backend
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-api
  namespace: prod
  labels:
    app: backend
spec:
  replicas: 4
  strategy:
    canary:
      activeService: backend-active
      canaryService: backend-canary
      steps:
        - setWeight: 20
        - pause: {} # Pauses until manually or automatically approved
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service.prod.svc.cluster.local"
            - name: DB_PORT
              value: "5432"